dist: focal
language: node_js
node_js:
  - 18

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"
  - node_modules/.cache

jobs:
  include:
    - name: "CI"
      script:
      - npx turbo run build lint stylelint test
      - npm run benchmark
    # - name: "Audit"
    #   script: npm audit || echo \"audit found some vulnerabilities.\"
    - if: tag =~ ^v # Run only for tags
      stage: "deploy"
      script:
        - if [[ "$TRAVIS_TAG" =~ "rc" ]] ; then export DIST_TAG="next" ; fi
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run release:publish
      skip_cleanup: true
    - if: tag =~ ^devtools-v # Run only for tags starting with devtools-v
      stage: "deploy"
      script:
        - CLIENT_ID=${CHROME_CLIENT_ID} CLIENT_SECRET=${CHROME_CLIENT_SECRET} REFRESH_TOKEN=${CHROME_REFRESH_TOKEN} EXTENSION_ID=${CHROME_EXTENSION_ID} npm run release:devtools
      skip_cleanup: true
