dist: focal
language: node_js

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"
  - node_modules/.cache

jobs:
  include:
    - name: "CI"
      script:
      - npx turbo run build lint stylelint test
      - npm run benchmark
    # - name: "Audit"
    #   script: npm audit || echo \"audit found some vulnerabilities.\"
    - if: branch =~ /^(master|next)$/
      stage: "deploy"
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run release:publish
      skip_cleanup: true
    - if: tag =~ /^@ima\/devtools@.*/ # Run only for @ima/devtools version tags
      stage: "deploy"
      script:
        - CLIENT_ID=${CHROME_CLIENT_ID} CLIENT_SECRET=${CHROME_CLIENT_SECRET} REFRESH_TOKEN=${CHROME_REFRESH_TOKEN} EXTENSION_ID=${CHROME_EXTENSION_ID} npm run release:devtools
      skip_cleanup: true
